version: '3.8'

services:
  # Template for MCP servers
  # example-mcp:
  #   build:
  #     context: ./servers/example
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PORT=8080
  #   restart: unless-stopped
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data:
    driver: local
